Feature/#10/avatar
0NYE/FPS-frontend pull request #11
Opened 2023-05-11 09:56 UTC by mubun

## Related Issues
#10 Avatar 기능구현

## Description

Wrapper, StyledAvatar를 통해 Avatar컴포넌트 구현
Size별로 이미지 크기 조절

//이미지 받아서 프로필 이미지 변경//

## To Reviewers

png 파일을 받아서 하면 원하는대로 기능이 구현되는데
링크를 받아서 StyledAvatar에 전달하니까 구현이 안되네요..

저는 Avatar.styles.jsx에 16번줄처럼 backgroundImg를 props로 설정하고
Avatar.component.jsx에 25번처럼 받아온 이미지를 전달하면 될 줄 알았는데

혹시 제가 잘못 접근한걸까요..?

2023-05-17 10:39 UTC, jjiny0716 requested changes
잘 안되는걸 되게 해보려고 노력하신 흔적이 보입니다. 수고 많으셨습니다 ㅠㅠ

2023-05-17 10:39 UTC, jjiny0716 commented on src/components/Avatar/Avatar.styles.jsx
> +  flex-direction: column;
크기를 고정으로 주는게 낫지 않을까요? 혹은 아얘 없애도 좋을 것 같아요.
Wrapper 안에 img 하나만 있기 때문에 flex도 불필요해 보입니다. 혹시 가운데 정렬을 하시려고 한걸까요?

2023-05-17 10:39 UTC, jjiny0716 commented on src/components/Avatar/Avatar.css
> +};
동그랗게 만드는게 잘 안되서 css로 해결을 하신 것 같습니다. 
`Wrapper`에 `border-radius: 50%;`를 주고, `overflow: hidden;`을 해서 밖으로 삐져나간 img를 가리면 어떨까요?

2023-05-17 10:39 UTC, jjiny0716 commented on src/components/Avatar/Avatar.component.jsx
> +  const [Image, setImage] = useState("https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png")
이렇게하면 기본 이미지 이외의 Avatar를 사용하지 못합니다.
props로 이미지의 url을 받는 것은 어떨까요?

2023-05-17 10:39 UTC, jjiny0716 commented on src/components/Avatar/Avatar.component.jsx
> +      >
styled-components로 잘 구현이 안되셨던 걸까요? 의미가 궁금합니다.

2023-05-17 10:39 UTC, jjiny0716 commented on src/App.jsx
이 파일은 왜 tsx에서 jsx가 된걸까요 ㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜ

2023-05-17 10:46 UTC, mubun commented on src/components/Avatar/Avatar.styles.jsx
> +  flex-direction: column;
제가 의도에 맞지 않게 기능을 사용했던 것 같습니다.
오늘 중으로 수정해서 다시 올려보겠습니다

2023-05-17 10:50 UTC, mubun commented on src/components/Avatar/Avatar.css
> +};
오 좋은아이디어인 것 같습니다. 한 번 시도해보겠습니다

2023-05-17 10:51 UTC, mubun commented on src/components/Avatar/Avatar.component.jsx
> +  const [Image, setImage] = useState("https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png")
죄송합니다. 자꾸 테스트해보고 props로 수정을 안하네요.
이 부분 역시 수정하겠습니다

2023-05-17 10:51 UTC, mubun commented on src/components/Avatar/Avatar.component.jsx
> +      >
정확합니다..
다른 컴포넌트 구현 완성되고 바로 styled-component로 만들어보겠습니다

2023-05-17 10:52 UTC, mubun commented on src/App.jsx
어..?
이건 저도 모르겠네요..
tsx파일로 바꾸겠습니다.

2023-05-17 11:37 UTC, mubun commented on src/App.jsx
바꾸고나니까 jsx파일이 적용이 안 되는데
이거 해결방법이 있을까요??

2023-05-18 16:07 UTC, jjiny0716 approved these changes

2023-05-18 16:07 UTC, merged