ProblemList 컴포넌트 구현
0NYE/FPS-frontend pull request #13
Opened 2023-05-17 10:23 UTC by mubun

## Related Issues
#12 

## Description
problemBox구현
상태에따라 성공,실패 svg변경
적용된 언어에따라 해당 언어 svg적용

## To Reviewers
svg는 margin값 줘도 적용이 안되는 것 같아서 그냥 공백을 추가해서 표시했는데
이는 다시 해결해보겠습니다.

직관적으로 태그 이름을 작성해보려고 했는데 이해 안되는 태그나 컴포넌트가 있다면
물어봐주세요!

html,css,js가 다 쓰일 것 같지는 않아서 useState에 상태 넣어서 true일때만 보이게 하려하는데
괜찮나요?

2023-05-17 10:58 UTC, jjiny0716 requested changes
수고 많으셨습니다.
+포맷팅이 안되어있네요 나중에 제가 싹다 포맷팅하겠습니답

2023-05-17 10:58 UTC, jjiny0716 commented on src/components/Problem/Problem.component.jsx
> +const Problem = ({title,bookmark,like,dislike,successrate,name,content})=>{
name 의미가 모호합니다. 문제 제작자를 표현하는 이름으로 바꾸는 것이 좋아보입니다.
makerNickname?? author?

2023-05-17 10:58 UTC, jjiny0716 commented on src/components/Problem/Problem.component.jsx
> +            )}
&&를 이용하면 어떨까요?

2023-05-17 10:58 UTC, jjiny0716 commented on src/components/Problem/Problem.component.jsx
> +    const [isJS,setIsJS] =useState(true);
해당 내용 전부다 props로 받아오는 것이 좋겠습니다.
+ 언어는 배열로 접근해보시는게 어떨까요? 이렇게 코드를 구성하면, 지원 언어가 늘어날 때마다 점점점 코드가 늘어나서 관리하기 힘들 것 같아요!

2023-05-17 10:58 UTC, jjiny0716 commented on src/components/Problem/Problem.styles.jsx
> +    display:inline-block;
div 요소들에 inline-block 값을 주신 이유가 궁금해요!

2023-05-17 10:58 UTC, jjiny0716 commented on src/components/Problem/Problem.component.jsx
> +                <Like width="20px" height="16px"/>{like+'    '}
다른 요소와의 거리를 두기 위해 공백을 추가하신 걸까요? margin을 이용하는 것은 어떨까요.

2023-05-17 10:58 UTC, jjiny0716 commented on src/components/Problem/Problem.component.jsx
> +            </TagData>
태그가 여러개인 상황에 대응하지 못할 것 같습니다. content를 배열로 처리하시는건 어떨까요?

2023-05-17 10:58 UTC, jjiny0716 commented on src/components/Avatar/Avatar.styles.jsx
> +
PR에 Avatar가 들어있는 걸로 봐선 여기 브랜치를 생성하실 때 develop에서 하시지 않은 것 같습니다. ㅠㅠ

2023-05-17 11:15 UTC, mubun commented on src/components/Problem/Problem.component.jsx
> +    const [isJS,setIsJS] =useState(true);
이 부분은 잘 이해가 안되는데 추가로 설명해주실 수 있나요?

2023-05-17 11:31 UTC, mubun commented on src/components/Avatar/Avatar.styles.jsx
> +
어 이제 보니까 git checkout feature/#10/Avatar같은건 이동이 잘되는데
git checkout develop하면 The following untracked working tree files would be overwritten by checkout
이런 오류가 발생하고 있었네요. 저는 여지껏 되는건 줄 알았는데 안되고 있었나보네요..
다시 해보겠습니다

2023-05-17 11:54 UTC, jjiny0716 commented on src/components/Problem/Problem.component.jsx
> +    const [isJS,setIsJS] =useState(true);
languages를 props로 받는거죠.
<ProblemBlock languages=["HTML", "CSS", "JS"]></ProblemBlock>
이후 내부 코드에서 배열을 돌면서 각 언어에 해당하는 아이콘을 렌더링!

2023-05-17 11:58 UTC, mubun commented on src/components/Problem/Problem.component.jsx
> +    const [isJS,setIsJS] =useState(true);
아 알겠습니당 적용해볼게요!

2023-05-17 11:59 UTC, mubun commented on src/components/Problem/Problem.component.jsx
> +                <Like width="20px" height="16px"/>{like+'    '}
svg에 마진을 적용해봤는데 안되더라구요
그래서 저렇게 임시방편으로 했습니다

2023-05-17 12:01 UTC, mubun commented on src/components/Problem/Problem.component.jsx
> +            </TagData>
아 그렇겠군요. 알겠습니당

2023-05-17 14:17 UTC, mubun commented on src/components/Problem/Problem.styles.jsx
> +    display:inline-block;
늦게 답변 드려 죄송합니다.
inline-block이 태그 안에 있는 요소들에 맞게 크기를 맞춰주는 것 같아서 넣었는데
좀 이상한가요..?

2023-05-18 13:01 UTC, jjiny0716 approved these changes

2023-05-18 13:02 UTC, jjiny0716 commented on src/components/ProblemBlock/ProblemBlock.component.tsx
> +  );
제가 수정해봤는데 길이가 어마무시하네요. 좀 생각해보고 필요하면 리팩토링 해야겠어요~

2023-05-18 16:11 UTC, merged