CommentInput 컴포넌트 구현
0NYE/FPS-frontend pull request #25
Opened 2023-05-19 12:41 UTC by mubun

## Related Issues
#22
## Description
댓글 입력 박스 구현
버튼 클릭시 댓글창에 게시
## To Reviewers
input안에 content가 가운데로 고정이 됐는데 어떻게 푸는 지 모르겠어서
일단 보류햇습니다. 나머지는 괜찮은 것 같아서 pr올렸습니다.

2023-05-22 10:41 UTC, jjiny0716 requested changes
수고 많으셨습니다!

2023-05-22 10:41 UTC, jjiny0716 commented on src/components/CommentInput/CommentInput.styles.jsx
> +export const InputBox=styled.input`
input은 여러줄 입력이 안됩니다. textarea를 사용해보시는 것은 어떨까요?

2023-05-22 10:41 UTC, jjiny0716 commented on src/components/CommentInput/CommentInput.component.jsx
> +const CommentInput=()=>{
onSubmit 함수를 외부에서 받는 것은 어떨까요?
`(value: string) => {}`
이걸 받아서 button의 onClick에 onSubmit을 연결하는 거죠! 이렇게 하면 외부에서 댓글 업로드같은 로직을 주입해서 사용할 수 있습니다.

2023-05-22 10:41 UTC, jjiny0716 commented on src/components/CommentInput/CommentInput.component.jsx
> +    </ButtonWrapper>
ButtonWrapper를 쓰신 이유가 궁금합니다. Button으로 충분하지 않으셨을까요?

2023-05-22 11:24 UTC, mubun commented on src/components/CommentInput/CommentInput.styles.jsx
> +export const InputBox=styled.input`
아 그런 차이가 있군요 수정하겠습니다

2023-05-22 11:25 UTC, mubun commented on src/components/CommentInput/CommentInput.component.jsx
> +const CommentInput=()=>{
좋은 정보 감사합니다

2023-05-22 11:26 UTC, mubun commented on src/components/CommentInput/CommentInput.component.jsx
> +    </ButtonWrapper>
저 때 제가 디자인 작업한다고 여러가지 태그를 추가하다보니 혼동이 온 것 같습니다
뭔가를 빼면 꼬일것같아서 둔 건데 빼도 된다면 바로 빼보겠습니다

2023-05-24 06:30 UTC, jjiny0716 approved these changes

2023-05-24 06:30 UTC, merged