Comment 컴포넌트 구현
0NYE/FPS-frontend pull request #27
Opened 2023-05-19 15:38 UTC by mubun

## Related Issues
#26 
## Description
#24 commentInput에서 받은 내용 게시
UI알맞게 배치
## To Reviewers
뭔가 비슷하게 한다고는 했는데 어설픈것 같네요..
수정할 부분 있으면 말씀해주세요!
+
Comment.svg가 #24,#26을 만들면서 2번 커밋하게 됐는데 상관없나요?

2023-05-22 10:44 UTC, jjiny0716 requested changes
svg 2번 커밋한거 상관 없습니다!
수고 많으셨고 요청사항 수정해주시면 됩니다.
세세한 스타일링은 제가 수정하겠습니다.

2023-05-22 10:44 UTC, jjiny0716 commented on src/components/Comment/Comment.component.jsx
> +  min,
여기도 Date를 쓰면 좋을 것 같네요!

2023-05-22 10:44 UTC, jjiny0716 commented on src/components/Comment/Comment.component.jsx
> +  userName,
userName과 avatarUrl을 받아야 아바타 이미지를 표시할 수 있을 것 같습니다.

2023-05-22 11:26 UTC, mubun commented on src/components/Comment/Comment.component.jsx
> +  userName,
아 그렇네요 수정하겠습니다.

2023-05-22 11:26 UTC, mubun commented on src/components/Comment/Comment.component.jsx
> +  min,
넵 바로 반영하겠습니다

2023-05-24 11:28 UTC, jjiny0716 approved these changes

2023-05-24 11:29 UTC, merged