HistoryBlock 컴포넌트 구현
0NYE/FPS-frontend pull request #29
Opened 2023-05-21 08:30 UTC by mubun

## Related Issues
#28 
## Description
Mypage에서 내가 쓴 글을 확인할 수 있도록 하는 블럭입니다

## To Reviewers
HistoryLayout에 betweenspace주고
title,time태그로 div를 나눴습니다.
그런데 time에 쓸 시간을 year,mon,day로 받아서 쓰는게 맞는지 궁금합니다

2023-05-22 10:45 UTC, jjiny0716 requested changes
Date 객체 쓰시면 고민하시는게 해결될 것 같습니다. 수고하셨습니다!

2023-05-22 10:45 UTC, jjiny0716 commented on src/components/HistoryBlock/HistoryBlock.component.jsx
> +    min
Date 객체 쓰시면 되요!

2023-05-22 10:45 UTC, jjiny0716 commented on src/components/HistoryBlock/HistoryBlock.component.jsx
> +            <HistoryTitle>{title}</HistoryTitle>
Tab이 또 4칸이 되어버렸네요 ㅠㅠ

2023-05-22 11:27 UTC, mubun commented on src/components/HistoryBlock/HistoryBlock.component.jsx
> +    min
덕분에 많이 배웠습니다

2023-05-22 11:28 UTC, mubun commented on src/components/HistoryBlock/HistoryBlock.component.jsx
> +            <HistoryTitle>{title}</HistoryTitle>
이게 파일을 만들고 공백을 수정해야하더라구요..
원래는 바로 수정했는데 이번에 깜빡했습니다.
이 부분도 바로 수정하겠습니다.

2023-05-22 11:48 UTC, jjiny0716 commented on src/components/HistoryBlock/HistoryBlock.component.jsx
> +            <HistoryTitle>{title}</HistoryTitle>
설정에서 기본 값을 바꾸시는게 좋을 것 같습니다.

2023-05-22 13:27 UTC, mubun commented on src/components/HistoryBlock/HistoryBlock.component.jsx
> +            <HistoryTitle>{title}</HistoryTitle>
신경써주셔서 감사합니당

2023-05-24 11:39 UTC, jjiny0716 approved these changes

2023-05-24 11:39 UTC, merged