FileSubmitButton컴포넌트 구현
0NYE/FPS-frontend pull request #31
Opened 2023-05-22 10:04 UTC by mubun

## Related Issues
#30 
## Description
파일제출버튼입니다
파일 제출 시 이름 및 색 변경
## To Reviewers

2023-05-22 10:48 UTC, jjiny0716 requested changes
수고 많으셨습니다!

2023-05-22 10:48 UTC, jjiny0716 commented on src/components/FileSubmissionButton/FileSubmissionButton.component.jsx
> +    console.log(files);
console.log 지워주시면 감사하겠습니다.

2023-05-22 10:48 UTC, jjiny0716 commented on src/components/FileSubmissionButton/FileSubmissionButton.component.jsx
> +        html제출
이렇게 하면 다른 파일 제출(css, js) 버튼을 만드는게 불가능해집니다. 받을 파일 타입을 props로 받아보는 것은 어떨까요?

2023-05-22 11:28 UTC, mubun commented on src/components/FileSubmissionButton/FileSubmissionButton.component.jsx
> +    console.log(files);
아차차.. 또 테스트하고 수정을 안했네요
바로 지우겠습니다.

2023-05-22 11:29 UTC, mubun commented on src/components/FileSubmissionButton/FileSubmissionButton.component.jsx
> +        html제출
isFieSubmitted를 props로 받으라는 말씀이신가요??

2023-05-22 11:52 UTC, jjiny0716 commented on src/components/FileSubmissionButton/FileSubmissionButton.component.jsx
> +        html제출
아 라인이 여러개가 잡혔네요 죄송해요
"html제출" 텍스트하고 아래 링크 들어가보시면
https://developer.mozilla.org/ko/docs/Web/HTML/Element/input/file 
정해진 파일 타입만 받도록 accept 속성(`accept="image/png, image/jpeg"`)을 주고있는 것을 확인하실 수 있는데, 그걸 주는게 좋을 것 같습니다.

2023-05-24 12:58 UTC, jjiny0716 approved these changes

2023-05-24 12:58 UTC, merged