SubmissonBlock컴포넌트 구현
0NYE/FPS-frontend pull request #33
Opened 2023-05-23 12:07 UTC by mubun

## Related Issues
#32 
## Description
통과여부 받아서 전시
심사기준에 따른 점수들을 CircleChart로 전시
UI알맞게 배치 
## To Reviewers
avatarURL을 마땅한 것을 찾지 못해 이 부분 테스트 못햇습니다.
추가적으로 다른 수정사항있다면 말씀해주세요!

2023-05-23 14:51 UTC, jjiny0716 requested changes
수고 많으셨습니다!

2023-05-23 14:51 UTC, jjiny0716 commented on src/components/SubmissionBlock/SubmissionBlock.component.jsx
> +  const currentDate = new Date();
현재 시각이 아니라, 문제 제출 시각을 Props로 받아야할 것 같습니다!

2023-05-23 14:51 UTC, jjiny0716 commented on src/components/SubmissionBlock/SubmissionBlock.component.jsx
> +    <>
fragment는 리액트 컴포넌트가 하나의 JSX를 반환해야 하기 때문에 한번 감싸줘야할 때 사용하는 것으로 알고있는데, 해당 코드에서 fragment가 사용된 이유가 무엇일까요?

2023-05-23 14:51 UTC, jjiny0716 commented on src/components/SubmissionBlock/SubmissionBlock.component.jsx
> +  };
굳이 함수로 만들어두지 말고, 총점을 바로 계산해서 변수에 저장해두는 것은 어떨까요?
추가로, 배열 고차함수(map, filter, reduce)를 공부해보시면 해당 코드를 개선할 수 있을 것 같습니다. 물론 해당 코드가 틀린 것은 아닙니다! 전에 알려드린대로 잘 하셨어요~

2023-05-23 14:51 UTC, jjiny0716 commented on src/components/SubmissionBlock/SubmissionBlock.component.jsx
> +          {Object.entries(metricScores).map(([string, number]) => (
string, number도 틀린 이름은 아니지만, 이것도 변수(매개변수)니까, 잘 표현할 수 있는 변수 이름을 지어보는 것도 좋을 것 같습니다!

2023-05-23 14:51 UTC, jjiny0716 commented on src/components/SubmissionBlock/SubmissionBlock.styles.jsx
> +  color:${({ isSuccess }) => (isSuccess ? `${colors.green}` : `${colors.red}`)}
굳이 템플릿 리터럴로 감쌀 필요가 있었을까요? 다른 곳도 같은 형식의 코드가 보입니다.

2023-05-23 14:51 UTC, jjiny0716 commented on src/components/SubmissionBlock/SubmissionBlock.styles.jsx
> +  color:${colors.grey1}
styled-components에서 제공하는 문법을 쓰면 굳이 import 해오지 않아도 될 것 같긴 합니다.

2023-05-23 15:20 UTC, mubun commented on src/components/SubmissionBlock/SubmissionBlock.component.jsx
> +    <>
저도 몰랐네요 바로 수정하겠습니다

2023-05-23 15:22 UTC, mubun commented on src/components/SubmissionBlock/SubmissionBlock.component.jsx
> +  };
이 부분은 이해가 잘 안되네요..
metricscores는 객체배열이라 총점을 구하기 위해서는 저런 계산하는 함수가 필수라 생각했습니다
총점을 바로 계산하는게 가능한가요??

2023-05-23 15:23 UTC, mubun commented on src/components/SubmissionBlock/SubmissionBlock.component.jsx
> +          {Object.entries(metricScores).map(([string, number]) => (
아 items,index처럼 그냥 일반적으로 쓰는건줄 알았습니다.
바꿔도 된다면 말씀하신대로 지어보겠습니다

2023-05-23 15:25 UTC, mubun commented on src/components/SubmissionBlock/SubmissionBlock.styles.jsx
> +  color:${({ isSuccess }) => (isSuccess ? `${colors.green}` : `${colors.red}`)}
아 저게 원래는 props.theme.colors.green 이런 형식이었다가 오늘 말씀드린것처럼
갑자기 global 그게 안먹혀서 해결방법 모색하다 저런 결과가 나온 것 같습니다
템플릿 리터럴은 지우도록 하겠습니다.

2023-05-23 15:26 UTC, mubun commented on src/components/SubmissionBlock/SubmissionBlock.styles.jsx
> +  color:${colors.grey1}
colors 임포트 안해도 된다는 말씀이신가요??

2023-05-23 15:28 UTC, mubun commented on src/components/SubmissionBlock/SubmissionBlock.component.jsx
> +  const currentDate = new Date();
그럼 props로 Date객체를 받으면 그 시간이 문제 제출 시각이라
해결 될 것 같은데 제가 생각한게 맞을까요??

2023-05-24 04:41 UTC, jjiny0716 commented on src/components/SubmissionBlock/SubmissionBlock.component.jsx
> +  const currentDate = new Date();
네 맞습니다!

2023-05-24 04:42 UTC, jjiny0716 commented on src/components/SubmissionBlock/SubmissionBlock.styles.jsx
> +  color:${colors.grey1}
넵

2023-05-24 04:44 UTC, jjiny0716 commented on src/components/SubmissionBlock/SubmissionBlock.component.jsx
> +  };
`const totalScore = Object.values(metricScores).reduce((totalScore, score) => totalScore + score);`
한 후 나중에 totalScore가 필요할 때 calculateTotalScore를 호출하는 게 아니라, totalScore를 바로 쓰면 됩니다.

2023-05-24 08:21 UTC, mubun commented on src/components/SubmissionBlock/SubmissionBlock.component.jsx
> +  };
아 그런뜻이었군요 이해했습니다. 감사합니당

2023-05-24 13:55 UTC, jjiny0716 approved these changes

2023-05-24 13:56 UTC, merged