"Checkbox 컴포넌트 구현시도""
0NYE/FPS-frontend pull request #6
Opened 2023-05-04 15:48 UTC by mubun

This reverts commit ceab81933b33b9839fa92cbebc54b604ae492b97.

## Related Issues

## Description

## To Reviewers

2023-05-05 12:16 UTC, jjiny0716 requested changes
react가 처음이라 힘드셨을 텐데, 고생 많으셨습니다.
조금만 수정하면 바로 사용할 수 있을 것 같습니다!
+ 브랜치 이름에 대해 이야기를 좀 해야할 것 같습니다.

2023-05-05 12:16 UTC, jjiny0716 commented on src/components/Checkbox/Checkbox.component.tsx
> +    label?: string | null;
label의 타입이 undefined, null, string 3가지가 되는데, 이를 의도하신 걸까요? 만약 의도하셨다면 undefined와 null은 각각 어느상황에 전달하는 걸까요?

2023-05-05 12:16 UTC, jjiny0716 commented on src/components/Checkbox/Checkbox.style.tsx
> +}
파일명은 컴포넌트이름.styles.tsx로 써주세요!
styles 파일에는 styled-components 라이브러리 이용해서 구현한 컴포넌트들이 들어가는 곳입니다.
+ 이 두 컴포넌트를 왜 구현하셨는지 궁금합니다. 그냥 component파일에 있는 Checkbox를 사용하면 안되는 걸까요?

2023-05-05 12:16 UTC, jjiny0716 commented on src/components/Checkbox/Checkbox.component.tsx
> +        <StyledCheckBox checked={checked}>
Checkbox와 CheckBox 둘중 하나로 통일하시는게 좋아보입니다!

2023-05-05 14:11 UTC, mubun commented on src/components/Checkbox/Checkbox.style.tsx
> +}
파일에대한 역할을 이해하지 못했던 것 같습니다 죄송합니다ㅠㅠ
+
제 의도는 그 App.tsx에서 불러올 때 <Checkbox id="checkbox" checked={isChecked} onChange={onChange} /> 이거를 다 써버리면 보기에 직관적이지 않아서 그냥 깔끔하게 <BasicCheckbox />만 보이는게 좀 더 직관적이지 않을까 해서 만든 것이었습니다.

2023-05-05 14:12 UTC, mubun commented on src/components/Checkbox/Checkbox.component.tsx
> +        <StyledCheckBox checked={checked}>
제가봐도 그런것 같네요 좋은의견 감사합니다:)

2023-05-05 14:13 UTC, mubun commented on src/components/Checkbox/Checkbox.component.tsx
> +    label?: string | null;
checkbox를 옆에 label이 없을때도 사용할 순간이 있지 않을까해서 string과 null을 만들었던 것이었는데 필요없다 생각되시면 그냥 없애버려도 상관없을 것 같습니다

2023-05-08 13:29 UTC, jjiny0716 commented on src/components/Checkbox/Checkbox.style.tsx
> +}
아하 그렇군요. 근데 지금 보시면 label에 늘보라고 써져있는데, label을 하드코딩하면 재사용이 사실상 불가능해집니다. 그럼 label을 또 props로 받아야하나 싶은데 그럴꺼면 그냥 Checkbox를 직접 사용하는게 더 편할 것 같아요.

2023-05-08 13:30 UTC, jjiny0716 commented on src/components/Checkbox/Checkbox.component.tsx
> +    label?: string | null;
label이 없을땐 undefined(안쓰기) vs null을 전달하기 둘중 뭘 해야하는걸까요?

2023-05-18 16:06 UTC, merged