Origin/feature/#4/drop down
0NYE/FPS-frontend pull request #7
Opened 2023-05-06 07:00 UTC by mubun

## Related Issues

## Description

## To Reviewers

2023-05-06 07:02 UTC, mubun commented
어 지금 보니까 checkbox랑 app.tsx가 커밋에 추가됐네요..
저 부분들은 삭제해도 될까요?

2023-05-08 13:42 UTC, jjiny0716 requested changes
고생하셨습니다. 해당 PR에 이전 작업 내용이 포함된건, #4번 브랜치를 생성하실때, develop 브랜치에서 생성한 것이 아니라, 이전에 작업하셨던 #3번 브랜치에서 바로 생성하셔서 그런 것 같습니다. 다음부턴 develop 브랜치에서 feature 브랜치를 생성해주시죠!

2023-05-08 13:42 UTC, jjiny0716 commented on src/components/dropdown/Dropdown.component.tsx
> +    const [selectItem, setSelectItem] = useState<string>("");
selectItem은 약간 동사(함수) 같은 느낌이 들어요. selectedItem은 어떨까요?

2023-05-08 13:42 UTC, jjiny0716 commented on src/components/dropdown/Dropdown.component.tsx
> +    };
그냥 변수에 배열로 저장해도 되지 않을까요?

2023-05-08 13:42 UTC, jjiny0716 commented on src/components/dropdown/Dropdown.component.tsx
> +    };
+
재사용이 불가능합니다. props로 item list를 받는 것을 고려해주세요 ~~ 왜냐하면 지석님이 고생해서 구현해주신 DropDownList 컴포넌트를 사용하고 싶은데, 제가 원하는 형태(다른 아이템들이 있는 DropDownList)로 사용할 수 없어서, 결국 코드를 수정해야합니다.

2023-05-08 13:42 UTC, jjiny0716 commented on src/components/dropdown/Dropdown.styles.tsx
> +  }
해당 css에 문제가 있는건 아니고, css 속성들의 순서를 각각 다르게 쓰고 계시기때문에, 순서를 한번 통일해보시면 좋을 것 같습니다. 예전에 제가 간단히 정리했던건데 한번 보시면 좋을 것 같습니다. 
https://puzzled-dingo-f69.notion.site/property-order-3baa3b2f53a24576838e8cce37420e5c

2023-05-08 13:42 UTC, jjiny0716 commented on src/components/dropdown/Ddown.tsx
Ddown은 무슨 뜻이죠?! 파일 내용을 좀더 잘 표현할 수 있는 이름으로 바꿔주시면 좋을 것 같습니다.

2023-05-15 10:17 UTC, mubun commented on src/components/dropdown/Dropdown.component.tsx
> +    const [selectItem, setSelectItem] = useState<string>("");
듣고보니 그렇네요. 참고하겠습니다.
좋은 의견 감사합니다:)

2023-05-15 10:18 UTC, mubun commented on src/components/dropdown/Dropdown.component.tsx
> +    };
아 죄송합니다. 제대로 작동하는 지 보고싶어서 그냥 정적으로 설정한것을 안바꿨네요
말씀하신대로 바꿔놓겠습니다

2023-05-15 10:19 UTC, mubun commented on src/components/dropdown/Dropdown.styles.tsx
> +  }
아 이런것도 있었군요. 너무 난잡하게 써서 보시는데 불편하셨겠네요.. 죄송합니다

2023-05-15 10:21 UTC, mubun commented on src/components/dropdown/Ddown.tsx
그렇네요.. 참고하겠습니다. 이미 논의했던 내용이지만
pr올릴때도 각각의 파일들이 무슨 역할을 한 건지도 적어서
리뷰하실 때 최대한 어려움 겪으시지 않도록 하겠습니다

2023-05-22 07:42 UTC, jjiny0716 commented
스타일이 의도한 바와 조금 다르긴 한데, 기능상 문제는 없으므로 일단 merge 하겠습니다.

2023-05-22 07:42 UTC, jjiny0716 approved these changes

2023-05-22 07:42 UTC, merged