Origin/reature/#5/search bar
0NYE/FPS-frontend pull request #8
Opened 2023-05-06 14:40 UTC by mubun

## Related Issues

## Description

## To Reviewers
검색기능까지 구현해보려고 했는데 생각보다 어려워서 우선 
스타일같이 비교적 간단히 구현된 부분만 올렸습니다. 빠른시일내에 완성시키겠습니다

2023-05-08 13:46 UTC, jjiny0716 requested changes
수고하셨습니다.

2023-05-08 13:46 UTC, jjiny0716 commented on src/components/Searchbar/Searchbar.styles.tsx
> +export const Glasses= styled.span`
glass가 무슨 뜻인가요??

2023-05-08 13:46 UTC, jjiny0716 commented on src/components/Searchbar/Searchbar.component.tsx
> +const Search = ()=>{
검색 기능을 구현을 하지 못하셨다고 하셨는데, 하실 필요가 없으십니다!! Search 컴포넌트가 외부에서 함수를 주입받아서, 텍스트를 칠때마다 전달받은 함수를 실행할 수 있게 하면 되지 않을까요? 검색 구현은 제가 할게요!

2023-05-15 10:13 UTC, mubun commented on src/components/Searchbar/Searchbar.styles.tsx
> +export const Glasses= styled.span`
늦게 답변드려서 죄송합니다
그 검색할 때 돋보기 그림을 클릭하면 검색기능이 진행되게하면 좋을 것 같다는 생각이 들어서
돋보기 모양을 만들기 위해 만든 태그(?)입니다.

Searchbar.component를 보시면, Glasses안에 circle과 line을 그리는 기능을 넣었습니다.
돋보기가 영어로 뭔지 생각이 안 나서 대충 Glasses라고 지었던 기억이 나네요..
 
 필요없다면 지우겠습니다

2023-05-15 10:16 UTC, mubun commented on src/components/Searchbar/Searchbar.component.tsx
> +const Search = ()=>{
구현해주신다니 감사합니다 ㅠㅠ
그런데 말씀해주신게 이해는 되는데 코드가 잘 그려지지는 않네요..

혹시 코드가 완성되면 pr올리실 때 코드가 작동하는 원리를
조금 자세히 설명해주실 수 있을까요??

시간이 없거나 곤란하시다면 그냥 올려주셔도 됩니다.
제가 따로 공부하겠습니다!

2023-05-18 08:48 UTC, mubun commented on src/assets/images/glass.svg
checkbox에 관해 질문했을 때였나
언젠가 svg파일을 자주 호출하면 안좋다고 해서
styled-component로 만들었던건데
이런건 그냥 svg파일로 받는 게 더 나은건가요?

2023-05-18 08:48 UTC, mubun commented on src/components/SearchBar/SearchBar.component.tsx
오 typescript에서는 이런식으로 props를 받는 거군요
배우고 갑니당

2023-05-18 08:48 UTC, mubun commented on src/components/SearchBar/SearchBar.component.tsx
근데 저거랑 string이랑 차이가 있는건가요??

2023-05-18 16:01 UTC, jjiny0716 approved these changes

2023-05-18 16:06 UTC, jjiny0716 commented on src/components/SearchBar/SearchBar.component.tsx
저거가 뭔지 모르겠습니다.

2023-05-18 16:06 UTC, merged